# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Likelihood maximisation for the GLMM 
#' 
#' Given model data and random effects samples `u`, this function will run the MCML steps to generate new estimates of 
#' mean function and covariance parameters
#' 
#' @details
#' Member function `$get_D_data()` of the covariance class will provide the necessary objects to specify the covariance matrix
#' 
#' @param D_data Named list specifying the covariance matrix D. Usually the return from the member function `get_D_data()` of the 
#' covariance class
#' @param Q Integer specifying the number of covariance parameters
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param cov_par_fix A vector of covariance parameters for importance sampling
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param start Vector of starting values for the optimisation
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=detailed output
#' @param mcnr Logical indicating whether to use Newton-Raphson (TRUE) or Expectation Maximisation (FALSE)
#' @return A vector of the parameters that maximise the likelihood functions
mcml_optim <- function(D_data, Q, Z, X, y, u, family, link, start, trace, mcnr = FALSE) {
    .Call(`_glmmrMCML_mcml_optim`, D_data, Q, Z, X, y, u, family, link, start, trace, mcnr)
}

#' Simulated likelihood optimisation step for MCML
#' 
#' @details
#' Member function `$get_D_data()` of the covariance class will provide the necessary objects to specify the covariance matrix
#' 
#' Likelihood maximisation for the GLMM
#' @param  D_data Named list specifying the covariance matrix D. Usually the return from the member function `get_D_data()` of the 
#' covariance class
#' @param Q Integer specifying the number of covariance parameters
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param cov_par_fix A vector of covariance parameters for importance sampling
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param start Vector of starting values for the optimisation
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=detailed output
#' @return A vector of the parameters that maximise the simulated likelihood
mcml_simlik <- function(D_data, Q, Z, X, y, u, family, link, start, trace) {
    .Call(`_glmmrMCML_mcml_simlik`, D_data, Q, Z, X, y, u, family, link, start, trace)
}

#' Likelihood maximisation for the GLMM using sparse matrix methods
#' 
#' Given model data and random effects samples `u`, this function will run the MCML steps to generate new estimates of 
#' mean function and covariance parameters
#' 
#' @details
#' Member function `$get_D_data()` of the covariance class will provide the necessary objects to specify the covariance matrix
#' 
#' Likelihood maximisation for the GLMM
#' @param  D_data Named list specifying the covariance matrix D. Usually the return from the member function `get_D_data()` of the 
#' covariance class
#' @param Q Integer specifying the number of covariance parameters
#' @param Ap Integer vector of pointers, one for each column, specifying the initial (zero-based) index of elements in the column. Slot `p`
#' of a matrix of a class defined in \link[Matrix]{sparseMatrix}
#' @param Ai Integer vector specifying the row indices of the non-zero elements of the matrix. Slot `i`
#' of a matrix of a class defined in \link[Matrix]{sparseMatrix}
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param cov_par_fix A vector of covariance parameters for importance sampling
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param start Vector of starting values for the optimisation
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=detailed output
#' @param mcnr Logical indicating whether to use Newton-Raphson (TRUE) or Expectation Maximisation (FALSE)
#' @param importance Logical indicating whether to use importance sampling step
#' @return A vector of the parameters that maximise the simulated likelihood
mcml_optim_sparse <- function(D_data, Q, Ap, Ai, Z, X, y, u, family, link, start, trace, mcnr = FALSE) {
    .Call(`_glmmrMCML_mcml_optim_sparse`, D_data, Q, Ap, Ai, Z, X, y, u, family, link, start, trace, mcnr)
}

#' Simulated likelihood optimisation step for MCML using sparse matrix methods
#' 
#' @details
#' Member function `$get_D_data()` of the covariance class will provide the necessary objects to specify the covariance matrix
#' 
#' Likelihood maximisation for the GLMM
#' @param  D_data Named list specifying the covariance matrix D. Usually the return from the member function `get_D_data()` of the 
#' covariance class
#' @param Q Integer specifying the number of covariance parameters
#' @param Ap Integer vector of pointers, one for each column, specifying the initial (zero-based) index of elements in the column. Slot `p`
#' of a matrix of a class defined in \link[Matrix]{sparseMatrix}
#' @param Ai Integer vector specifying the row indices of the non-zero elements of the matrix. Slot `i`
#' of a matrix of a class defined in \link[Matrix]{sparseMatrix}
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param cov_par_fix A vector of covariance parameters for importance sampling
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param start Vector of starting values for the optimisation
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=detailed output
#' @return A vector of the parameters that maximise the simulated likelihood
mcml_simlik_sparse <- function(D_data, Q, Ap, Ai, Z, X, y, u, family, link, start, trace) {
    .Call(`_glmmrMCML_mcml_simlik_sparse`, D_data, Q, Ap, Ai, Z, X, y, u, family, link, start, trace)
}

#' Generate Hessian matrix of GLMM
#' 
#' Generate Hessian matrix of GLMM using numerical differentiation
#' 
#' @details
#' Member function `$get_D_data()` of the covariance class will provide the necessary objects to specify the covariance matrix
#' 
#' @param  D_data Named list specifying the covariance matrix D. Usually the return from the member function `get_D_data()` of the 
#' covariance class
#' @param Q Integer specifying the number of covariance parameters
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param cov_par_fix A vector of covariance parameters for importance sampling
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param start Vector of starting values for the optimisation
#' @param tol The tolerance of the numerical differentiation routine
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=detailed output
#' @return The estimated Hessian matrix
mcml_hess <- function(D_data, Q, Z, X, y, u, family, link, start, tol = 1e-5, trace = 0L) {
    .Call(`_glmmrMCML_mcml_hess`, D_data, Q, Z, X, y, u, family, link, start, tol, trace)
}

#' Calculates the conditional Akaike Information Criterion for the GLMM
#' 
#' Calculates the conditional Akaike Information Criterion for the GLMM 
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param  D_data Named list specifying the covariance matrix D. Usually the return from the member function `get_D_data()` of the 
#' covariance class
#' @param beta_par Vector specifying the values of the mean function parameters to estimate the AIC at
#' @param cov_par Vector specifying the values of the covariance function parameters to estimate the AIC at
#' @return Estimated conditional AIC
aic_mcml <- function(Z, X, y, u, family, link, D_data, beta_par, cov_par) {
    .Call(`_glmmrMCML_aic_mcml`, Z, X, y, u, family, link, D_data, beta_par, cov_par)
}

