# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Markov Chain Monte Carlo Maximum Likelihood Algorithm 
#' 
#' Full Markov Chain Monte Carlo Maximum Likelihood Algorithm using c++ code and the inbuilt Hamiltonian Monte Carlo MCMC sampler.
#' 
#' @param cov An integer matrix with columns of block identifier, dimension of block, function definition, number of variables
#' in the argument to the funciton, and index of the parameters, respectively. Rows are specific functions of each block.
#' @param data Vector of data. Created by flattening the matrices in column-major order of the data used in each block.
#' @param eff_range Vector of values with the effective range parameters of the covariance functions, where required.
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param start Vector of starting values for the optimisation
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=ever more detailed output
#' @param mcnr Logical indicating whether to use Newton-Raphson (TRUE) or Expectation Maximisation (FALSE)
#' @param m Integer. Total number of MCMC samples to draw on each iteration
#' @param maxiter Integer. The maximum number of MCML iterations
#' @param warmup Integer. The number of warmup iterations for the MCMC sampler. Note, this reduces to 10 after
#' the first iteration as the sampler starts from the last set of values and adaptive step size
#' @param tol Value of the tolerance. The algorithm termninates if differences in values of parameters between
#' iterations are all less than this value.
#' @param verbose Logical indicating whether to provide output to the console
#' @param lambda Value of the trajectory length of the leapfrog integrator in Hamiltonian Monte Carlo
#'  (equal to number of steps times the step length). Larger values result in lower correlation in samples, but
#'  require larger numbers of steps and so is slower.
#' @param refresh Integer. Number of MCMC iterations to print progress to the console (requires verbose=TRUE)
#' @param maxsteps Integer. The maximum number of steps of the leapfrom integrator
#' @return A list with the maximum likelihood estimates of the model parameters, the final set of MCMC samples, and
#' and indciator for whether the algorithm converged.
mcml_full <- function(cov, data, eff_range, Z, X, y, family, link, start, mcnr = FALSE, m = 500L, maxiter = 30L, warmup = 500L, tol = 1e-3, verbose = TRUE, lambda = 0.05, trace = 0L, refresh = 500L, maxsteps = 100L) {
    .Call(`_glmmrMCML_mcml_full`, cov, data, eff_range, Z, X, y, family, link, start, mcnr, m, maxiter, warmup, tol, verbose, lambda, trace, refresh, maxsteps)
}

#' Hamiltonian Monte Carlo Sampler for Model Random Effects
#' 
#' Hamiltonian Monte Carlo Sampler for Model Random Effects
#' 
#' @param Z Matrix Z of the GLMM
#' @param L Matrix L, the Cholesky decomposition of the random effect covariance (returned with `gen_chol_D()` function of covariance)
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param beta Vector of parameters multiplying the X matrix
#' @param var_par (Optional) Value of the scale parameter where required (Gaussian and gamma distributions) 
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=ever more detailed output
#' @param nsamp Integer. Total number of MCMC samples to draw on each iteration
#' @param warmup Integer. The number of warmup iterations for the MCMC sampler. Note, this reduces to 10 after
#' the first iteration as the sampler starts from the last set of values and adaptive step size
#' @param lambda Value of the trajectory length of the leapfrog integrator in Hamiltonian Monte Carlo
#'  (equal to number of steps times the step length). Larger values result in lower correlation in samples, but
#'  require larger numbers of steps and so is slower.
#' @param refresh Integer. Number of MCMC iterations to print progress to the console (requires verbose=TRUE)
#' @param maxsteps Integer. The maximum number of steps of the leapfrom integrator
#' @return A matrix (of dimension number of random effects * number of samples)
mcmc_sample <- function(Z, L, X, y, beta, family, link, warmup, nsamp, lambda, var_par = 1, trace = 0L, refresh = 500L, maxsteps = 100L) {
    .Call(`_glmmrMCML_mcmc_sample`, Z, L, X, y, beta, family, link, warmup, nsamp, lambda, var_par, trace, refresh, maxsteps)
}

#' Likelihood maximisation for the GLMM 
#' 
#' Given model data and random effects samples `u`, this function will run the MCML steps to generate new estimates of 
#' mean function and covariance parameters
#' 
#' @details
#' Member function `$get_D_data()` of the covariance class will provide the necessary objects to specify the covariance matrix
#' 
#' @param cov An integer matrix with columns of block identifier, dimension of block, function definition, number of variables
#' in the argument to the funciton, and index of the parameters, respectively. Rows are specific functions of each block.
#' @param data Vector of data. Created by flattening the matrices in column-major order of the data used in each block.
#' @param eff_range Vector of values with the effective range parameters of the covariance functions, where required.
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param start Vector of starting values for the optimisation
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=detailed output
#' @param mcnr Logical indicating whether to use Newton-Raphson (TRUE) or Expectation Maximisation (FALSE)
#' @return A vector of the parameters that maximise the likelihood functions
mcml_optim <- function(cov, data, eff_range, Z, X, y, u, family, link, start, trace, mcnr = FALSE) {
    .Call(`_glmmrMCML_mcml_optim`, cov, data, eff_range, Z, X, y, u, family, link, start, trace, mcnr)
}

#' Simulated likelihood optimisation step for MCML
#' 
#' @details
#' Member function `$get_D_data()` of the covariance class will provide the necessary objects to specify the covariance matrix
#' 
#' Likelihood maximisation for the GLMM
#' @param cov An integer matrix with columns of block identifier, dimension of block, function definition, number of variables
#' in the argument to the funciton, and index of the parameters, respectively. Rows are specific functions of each block.
#' @param data Vector of data. Created by flattening the matrices in column-major order of the data used in each block.
#' @param eff_range Vector of values with the effective range parameters of the covariance functions, where required.
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param start Vector of starting values for the optimisation
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=detailed output
#' @return A vector of the parameters that maximise the simulated likelihood
mcml_simlik <- function(cov, data, eff_range, Z, X, y, u, family, link, start, trace) {
    .Call(`_glmmrMCML_mcml_simlik`, cov, data, eff_range, Z, X, y, u, family, link, start, trace)
}

#' Likelihood maximisation for the GLMM using sparse matrix methods
#' 
#' Given model data and random effects samples `u`, this function will run the MCML steps to generate new estimates of 
#' mean function and covariance parameters
#' 
#' @details
#' Member function `$get_D_data()` of the covariance class will provide the necessary objects to specify the covariance matrix
#' 
#' Likelihood maximisation for the GLMM
#' @param cov An integer matrix with columns of block identifier, dimension of block, function definition, number of variables
#' in the argument to the funciton, and index of the parameters, respectively. Rows are specific functions of each block.
#' @param data Vector of data. Created by flattening the matrices in column-major order of the data used in each block.
#' @param eff_range Vector of values with the effective range parameters of the covariance functions, where required.
#' @param Ap Integer vector of pointers, one for each column, specifying the initial (zero-based) index of elements in the column. Slot `p`
#' of a matrix of a class defined in \link[Matrix]{sparseMatrix}
#' @param Ai Integer vector specifying the row indices of the non-zero elements of the matrix. Slot `i`
#' of a matrix of a class defined in \link[Matrix]{sparseMatrix}
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param start Vector of starting values for the optimisation
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=detailed output
#' @param mcnr Logical indicating whether to use Newton-Raphson (TRUE) or Expectation Maximisation (FALSE)
#' @return A vector of the parameters that maximise the simulated likelihood
mcml_optim_sparse <- function(cov, data, eff_range, Ap, Ai, Z, X, y, u, family, link, start, trace, mcnr = FALSE) {
    .Call(`_glmmrMCML_mcml_optim_sparse`, cov, data, eff_range, Ap, Ai, Z, X, y, u, family, link, start, trace, mcnr)
}

#' Simulated likelihood optimisation step for MCML using sparse matrix methods
#' 
#' @details
#' Member function `$get_D_data()` of the covariance class will provide the necessary objects to specify the covariance matrix
#' 
#' Likelihood maximisation for the GLMM
#' @param cov An integer matrix with columns of block identifier, dimension of block, function definition, number of variables
#' in the argument to the funciton, and index of the parameters, respectively. Rows are specific functions of each block.
#' @param data Vector of data. Created by flattening the matrices in column-major order of the data used in each block.
#' @param eff_range Vector of values with the effective range parameters of the covariance functions, where required.
#' @param Ap Integer vector of pointers, one for each column, specifying the initial (zero-based) index of elements in the column. Slot `p`
#' of a matrix of a class defined in \link[Matrix]{sparseMatrix}
#' @param Ai Integer vector specifying the row indices of the non-zero elements of the matrix. Slot `i`
#' of a matrix of a class defined in \link[Matrix]{sparseMatrix}
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param start Vector of starting values for the optimisation
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=detailed output
#' @return A vector of the parameters that maximise the simulated likelihood
mcml_simlik_sparse <- function(cov, data, eff_range, Ap, Ai, Z, X, y, u, family, link, start, trace) {
    .Call(`_glmmrMCML_mcml_simlik_sparse`, cov, data, eff_range, Ap, Ai, Z, X, y, u, family, link, start, trace)
}

#' Generate Hessian matrix of GLMM
#' 
#' Generate Hessian matrix of GLMM using numerical differentiation
#' 
#' @details
#' Member function `$get_D_data()` of the covariance class will provide the necessary objects to specify the covariance matrix
#' 
#' @param cov An integer matrix with columns of block identifier, dimension of block, function definition, number of variables
#' in the argument to the funciton, and index of the parameters, respectively. Rows are specific functions of each block.
#' @param data Vector of data. Created by flattening the matrices in column-major order of the data used in each block.
#' @param eff_range Vector of values with the effective range parameters of the covariance functions, where required.
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param start Vector of starting values for the optimisation
#' @param tol The tolerance of the numerical differentiation routine
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=detailed output
#' @return The estimated Hessian matrix
mcml_hess <- function(cov, data, eff_range, Z, X, y, u, family, link, start, tol = 1e-5, trace = 0L) {
    .Call(`_glmmrMCML_mcml_hess`, cov, data, eff_range, Z, X, y, u, family, link, start, tol, trace)
}

#' Generate Hessian matrix of GLMM using sparse matrix methods
#' 
#' Generate Hessian matrix of GLMM with numerical differentiation using sparse matrix methods
#' 
#' @details
#' Member function `$get_D_data()` of the covariance class will provide the necessary objects to specify the covariance matrix
#' 
#' @param cov An integer matrix with columns of block identifier, dimension of block, function definition, number of variables
#' in the argument to the funciton, and index of the parameters, respectively. Rows are specific functions of each block.
#' @param data Vector of data. Created by flattening the matrices in column-major order of the data used in each block.
#' @param eff_range Vector of values with the effective range parameters of the covariance functions, where required.
#' @param Ap Integer vector of pointers, one for each column, specifying the initial (zero-based) index of elements in the column. Slot `p`
#' of a matrix of a class defined in \link[Matrix]{sparseMatrix}
#' @param Ai Integer vector specifying the row indices of the non-zero elements of the matrix. Slot `i`
#' of a matrix of a class defined in \link[Matrix]{sparseMatrix}
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param start Vector of starting values for the optimisation
#' @param tol The tolerance of the numerical differentiation routine
#' @param trace Integer indicating what to report to the console, 0= nothing, 1-3=detailed output
#' @return The estimated Hessian matrix
mcml_hess_sparse <- function(cov, data, eff_range, Ap, Ai, Z, X, y, u, family, link, start, tol = 1e-5, trace = 0L) {
    .Call(`_glmmrMCML_mcml_hess_sparse`, cov, data, eff_range, Ap, Ai, Z, X, y, u, family, link, start, tol, trace)
}

#' Calculates the conditional Akaike Information Criterion for the GLMM
#' 
#' Calculates the conditional Akaike Information Criterion for the GLMM 
#' @param cov An integer matrix with columns of block identifier, dimension of block, function definition, number of variables
#' in the argument to the funciton, and index of the parameters, respectively. Rows are specific functions of each block.
#' @param data Vector of data. Created by flattening the matrices in column-major order of the data used in each block.
#' @param eff_range Vector of values with the effective range parameters of the covariance functions, where required.
#' @param Z Matrix Z of the GLMM
#' @param X Matrix X of the GLMM
#' @param y Vector of observations
#' @param u Matrix of samples of the random effects. Each column is a sample.
#' @param family Character specifying the family
#' @param link Character specifying the link function
#' @param beta_par Vector specifying the values of the mean function parameters to estimate the AIC at
#' @param cov_par Vector specifying the values of the covariance function parameters to estimate the AIC at
#' @return Estimated conditional AIC
aic_mcml <- function(cov, data, eff_range, Z, X, y, u, family, link, beta_par, cov_par) {
    .Call(`_glmmrMCML_aic_mcml`, cov, data, eff_range, Z, X, y, u, family, link, beta_par, cov_par)
}

#' Multivariate normal log likelihood
#' 
#' Calculates the log likelihood of the multivariate normal distribution using `glmmr` covariance representation
#' 
#' @param cov An integer matrix with columns of block identifier, dimension of block, function definition, number of variables
#' in the argument to the funciton, and index of the parameters, respectively. Rows are specific functions of each block.
#' @param data Vector of data. Created by flattening the matrices in column-major order of the data used in each block.
#' @param eff_range Vector of values with the effective range parameters of the covariance functions, where required.
#' @param gamma Vector specifying the values of the covariance function parameters
#' @param u Matrix (or vector) of observed values
#' @return Scalar value 
mvn_ll <- function(cov, data, eff_range, gamma, u) {
    .Call(`_glmmrMCML_mvn_ll`, cov, data, eff_range, gamma, u)
}

